
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: the_jetsetter_wallet_development

test:
  <<: *default
  database: the_jetsetter_wallet_test


production:
  <<: *default
  database: the_jetsetter_wallet_production
  username: the_jetsetter_wallet
  password: <%= ENV['THE_JETSETTER_WALLET_DATABASE_PASSWORD'] %>
